version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    restart: always 
    image: mongo:3
    networks:
      - graylog
    volumes:
      - ./mongo_data:/data/db
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - graylog
    ports:
      - 9200:9200
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    restart: always
    image: graylog/graylog:3.3.5
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.mydomain.ru/
    networks:
      - graylog
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF HTTP
      - 12202:12202
      # GELF UDP
      - 12201:12201/udp
      - 5044:5044/tcp
      - 2055:2055/udp
    volumes:
      # Mount local configuration directory into Docker container
      - ./graylog/config:/usr/share/graylog/data/config
      - ./graylog/journal:/usr/share/graylog/data/journal
      - ./graylog/plugin:/usr/share/graylog/plugin
networks:
  graylog:
    driver: bridge


# volumes:
#   mongo_data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ./mongo_data
#   es_data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ./es_data
#   graylog_journal:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ./graylog
